// Code generated by protoc-gen-go. DO NOT EDIT.
// source: lagu_sion.proto

package lagusion

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SortOptions int32

const (
	SortOptions_NUMBER   SortOptions = 0
	SortOptions_ALPHABET SortOptions = 1
)

var SortOptions_name = map[int32]string{
	0: "NUMBER",
	1: "ALPHABET",
}

var SortOptions_value = map[string]int32{
	"NUMBER":   0,
	"ALPHABET": 1,
}

func (x SortOptions) String() string {
	return proto.EnumName(SortOptions_name, int32(x))
}

func (SortOptions) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4ac555336d8700ef, []int{0}
}

type UUID struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UUID) Reset()         { *m = UUID{} }
func (m *UUID) String() string { return proto.CompactTextString(m) }
func (*UUID) ProtoMessage()    {}
func (*UUID) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ac555336d8700ef, []int{0}
}

func (m *UUID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UUID.Unmarshal(m, b)
}
func (m *UUID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UUID.Marshal(b, m, deterministic)
}
func (m *UUID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UUID.Merge(m, src)
}
func (m *UUID) XXX_Size() int {
	return xxx_messageInfo_UUID.Size(m)
}
func (m *UUID) XXX_DiscardUnknown() {
	xxx_messageInfo_UUID.DiscardUnknown(m)
}

var xxx_messageInfo_UUID proto.InternalMessageInfo

func (m *UUID) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Verse struct {
	Id                   *UUID    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Contents             string   `protobuf:"bytes,2,opt,name=contents,proto3" json:"contents,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Verse) Reset()         { *m = Verse{} }
func (m *Verse) String() string { return proto.CompactTextString(m) }
func (*Verse) ProtoMessage()    {}
func (*Verse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ac555336d8700ef, []int{1}
}

func (m *Verse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Verse.Unmarshal(m, b)
}
func (m *Verse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Verse.Marshal(b, m, deterministic)
}
func (m *Verse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Verse.Merge(m, src)
}
func (m *Verse) XXX_Size() int {
	return xxx_messageInfo_Verse.Size(m)
}
func (m *Verse) XXX_DiscardUnknown() {
	xxx_messageInfo_Verse.DiscardUnknown(m)
}

var xxx_messageInfo_Verse proto.InternalMessageInfo

func (m *Verse) GetId() *UUID {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Verse) GetContents() string {
	if m != nil {
		return m.Contents
	}
	return ""
}

type Book struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ShortName            string   `protobuf:"bytes,2,opt,name=short_name,json=shortName,proto3" json:"short_name,omitempty"`
	LongName             string   `protobuf:"bytes,3,opt,name=long_name,json=longName,proto3" json:"long_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Book) Reset()         { *m = Book{} }
func (m *Book) String() string { return proto.CompactTextString(m) }
func (*Book) ProtoMessage()    {}
func (*Book) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ac555336d8700ef, []int{2}
}

func (m *Book) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Book.Unmarshal(m, b)
}
func (m *Book) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Book.Marshal(b, m, deterministic)
}
func (m *Book) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Book.Merge(m, src)
}
func (m *Book) XXX_Size() int {
	return xxx_messageInfo_Book.Size(m)
}
func (m *Book) XXX_DiscardUnknown() {
	xxx_messageInfo_Book.DiscardUnknown(m)
}

var xxx_messageInfo_Book proto.InternalMessageInfo

func (m *Book) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Book) GetShortName() string {
	if m != nil {
		return m.ShortName
	}
	return ""
}

func (m *Book) GetLongName() string {
	if m != nil {
		return m.LongName
	}
	return ""
}

type Song struct {
	Id                   *UUID    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Number               uint32   `protobuf:"varint,2,opt,name=number,proto3" json:"number,omitempty"`
	Title                string   `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Verses               []*Verse `protobuf:"bytes,4,rep,name=verses,proto3" json:"verses,omitempty"`
	Reff                 *Verse   `protobuf:"bytes,5,opt,name=reff,proto3" json:"reff,omitempty"`
	Book                 *Book    `protobuf:"bytes,6,opt,name=book,proto3" json:"book,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Song) Reset()         { *m = Song{} }
func (m *Song) String() string { return proto.CompactTextString(m) }
func (*Song) ProtoMessage()    {}
func (*Song) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ac555336d8700ef, []int{3}
}

func (m *Song) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Song.Unmarshal(m, b)
}
func (m *Song) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Song.Marshal(b, m, deterministic)
}
func (m *Song) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Song.Merge(m, src)
}
func (m *Song) XXX_Size() int {
	return xxx_messageInfo_Song.Size(m)
}
func (m *Song) XXX_DiscardUnknown() {
	xxx_messageInfo_Song.DiscardUnknown(m)
}

var xxx_messageInfo_Song proto.InternalMessageInfo

func (m *Song) GetId() *UUID {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Song) GetNumber() uint32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *Song) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Song) GetVerses() []*Verse {
	if m != nil {
		return m.Verses
	}
	return nil
}

func (m *Song) GetReff() *Verse {
	if m != nil {
		return m.Reff
	}
	return nil
}

func (m *Song) GetBook() *Book {
	if m != nil {
		return m.Book
	}
	return nil
}

type ListSongRequest struct {
	BookId               uint32      `protobuf:"varint,1,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	SortOptions          SortOptions `protobuf:"varint,2,opt,name=sort_options,json=sortOptions,proto3,enum=lagusion.SortOptions" json:"sort_options,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ListSongRequest) Reset()         { *m = ListSongRequest{} }
func (m *ListSongRequest) String() string { return proto.CompactTextString(m) }
func (*ListSongRequest) ProtoMessage()    {}
func (*ListSongRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ac555336d8700ef, []int{4}
}

func (m *ListSongRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListSongRequest.Unmarshal(m, b)
}
func (m *ListSongRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListSongRequest.Marshal(b, m, deterministic)
}
func (m *ListSongRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListSongRequest.Merge(m, src)
}
func (m *ListSongRequest) XXX_Size() int {
	return xxx_messageInfo_ListSongRequest.Size(m)
}
func (m *ListSongRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListSongRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListSongRequest proto.InternalMessageInfo

func (m *ListSongRequest) GetBookId() uint32 {
	if m != nil {
		return m.BookId
	}
	return 0
}

func (m *ListSongRequest) GetSortOptions() SortOptions {
	if m != nil {
		return m.SortOptions
	}
	return SortOptions_NUMBER
}

type ListSongResponse struct {
	Songs                []*Song  `protobuf:"bytes,1,rep,name=songs,proto3" json:"songs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListSongResponse) Reset()         { *m = ListSongResponse{} }
func (m *ListSongResponse) String() string { return proto.CompactTextString(m) }
func (*ListSongResponse) ProtoMessage()    {}
func (*ListSongResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ac555336d8700ef, []int{5}
}

func (m *ListSongResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListSongResponse.Unmarshal(m, b)
}
func (m *ListSongResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListSongResponse.Marshal(b, m, deterministic)
}
func (m *ListSongResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListSongResponse.Merge(m, src)
}
func (m *ListSongResponse) XXX_Size() int {
	return xxx_messageInfo_ListSongResponse.Size(m)
}
func (m *ListSongResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListSongResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListSongResponse proto.InternalMessageInfo

func (m *ListSongResponse) GetSongs() []*Song {
	if m != nil {
		return m.Songs
	}
	return nil
}

func init() {
	proto.RegisterEnum("lagusion.SortOptions", SortOptions_name, SortOptions_value)
	proto.RegisterType((*UUID)(nil), "lagusion.UUID")
	proto.RegisterType((*Verse)(nil), "lagusion.Verse")
	proto.RegisterType((*Book)(nil), "lagusion.Book")
	proto.RegisterType((*Song)(nil), "lagusion.Song")
	proto.RegisterType((*ListSongRequest)(nil), "lagusion.ListSongRequest")
	proto.RegisterType((*ListSongResponse)(nil), "lagusion.ListSongResponse")
}

func init() { proto.RegisterFile("lagu_sion.proto", fileDescriptor_4ac555336d8700ef) }

var fileDescriptor_4ac555336d8700ef = []byte{
	// 411 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0x4f, 0x6f, 0xd3, 0x40,
	0x10, 0xc5, 0xeb, 0xd4, 0x31, 0xc9, 0xa4, 0x4d, 0xa2, 0x11, 0x7f, 0x4c, 0xf8, 0xa3, 0x6a, 0x41,
	0x6a, 0xc5, 0x21, 0x07, 0x73, 0xe9, 0xb5, 0xa1, 0x95, 0xa8, 0x14, 0x0a, 0x5a, 0x13, 0x38, 0x46,
	0x4e, 0xbd, 0x35, 0xab, 0x3a, 0x3b, 0xc1, 0xbb, 0xce, 0x47, 0xe4, 0x73, 0xa1, 0xdd, 0x4d, 0xe2,
	0x2a, 0x20, 0xf5, 0xf8, 0xf6, 0xe7, 0x79, 0x33, 0xef, 0xc9, 0x30, 0x28, 0xb3, 0xa2, 0x9e, 0x6b,
	0x49, 0x6a, 0xbc, 0xaa, 0xc8, 0x10, 0x76, 0xec, 0x83, 0xd5, 0xec, 0x35, 0x84, 0xb3, 0xd9, 0xf5,
	0x25, 0x3e, 0x85, 0xf6, 0x3a, 0x2b, 0x6b, 0x11, 0x07, 0x27, 0xc1, 0x59, 0x97, 0x7b, 0xc1, 0x3e,
	0x41, 0xfb, 0x87, 0xa8, 0xb4, 0xc0, 0xb7, 0xd0, 0x92, 0xb9, 0x63, 0xbd, 0xa4, 0x3f, 0xde, 0x4e,
	0x8f, 0xed, 0x28, 0x6f, 0xc9, 0x1c, 0x47, 0xd0, 0xb9, 0x25, 0x65, 0x84, 0x32, 0x3a, 0x6e, 0x39,
	0x87, 0x9d, 0x66, 0x1c, 0xc2, 0x09, 0xd1, 0x3d, 0xf6, 0x77, 0x1e, 0xc7, 0x6e, 0xe6, 0x0d, 0x80,
	0xfe, 0x45, 0x95, 0x99, 0xab, 0x6c, 0x29, 0x36, 0x53, 0x5d, 0xf7, 0x72, 0x93, 0x2d, 0x05, 0xbe,
	0x82, 0x6e, 0x49, 0xaa, 0xf0, 0xf4, 0xd0, 0x7b, 0xda, 0x07, 0x0b, 0xd9, 0x9f, 0x00, 0xc2, 0x94,
	0x54, 0xf1, 0xe8, 0x61, 0xcf, 0x21, 0x52, 0xf5, 0x72, 0x21, 0x2a, 0xb7, 0xe0, 0x98, 0x6f, 0x94,
	0xcd, 0x6b, 0xa4, 0x29, 0xb7, 0xce, 0x5e, 0xe0, 0x29, 0x44, 0x6b, 0x9b, 0x57, 0xc7, 0xe1, 0xc9,
	0xe1, 0x59, 0x2f, 0x19, 0x34, 0x8e, 0xae, 0x07, 0xbe, 0xc1, 0xf8, 0x0e, 0xc2, 0x4a, 0xdc, 0xdd,
	0xc5, 0x6d, 0xb7, 0xf8, 0x9f, 0xcf, 0x1c, 0x44, 0x06, 0xe1, 0x82, 0xe8, 0x3e, 0x8e, 0xf6, 0xaf,
	0xb3, 0x75, 0x70, 0xc7, 0x58, 0x0e, 0x83, 0xa9, 0xd4, 0xc6, 0x66, 0xe1, 0xe2, 0x77, 0x2d, 0xb4,
	0xc1, 0x17, 0xf0, 0xc4, 0xa2, 0xf9, 0xae, 0xac, 0xc8, 0xca, 0xeb, 0x1c, 0xcf, 0xe1, 0x48, 0xdb,
	0xbe, 0x68, 0x65, 0x24, 0x29, 0x5f, 0x74, 0x3f, 0x79, 0xd6, 0xf8, 0xa6, 0x54, 0x99, 0xaf, 0x1e,
	0xf2, 0x9e, 0x6e, 0x04, 0x3b, 0x87, 0x61, 0xb3, 0x45, 0xaf, 0x48, 0x69, 0x81, 0xef, 0xa1, 0xad,
	0x49, 0x15, 0x3a, 0x0e, 0x5c, 0xd4, 0xfe, 0x43, 0x1b, 0x55, 0x70, 0x0f, 0x3f, 0x9c, 0x42, 0xef,
	0x81, 0x2b, 0x02, 0x44, 0x37, 0xb3, 0x2f, 0x93, 0x2b, 0x3e, 0x3c, 0xc0, 0x23, 0xe8, 0x5c, 0x4c,
	0xbf, 0x7d, 0xbe, 0x98, 0x5c, 0x7d, 0x1f, 0x06, 0xc9, 0x4f, 0x18, 0x4c, 0xb3, 0xa2, 0x4e, 0x25,
	0xa9, 0x54, 0x54, 0x6b, 0x79, 0x2b, 0xf0, 0x12, 0xba, 0xdb, 0xad, 0x1a, 0x5f, 0x36, 0xfe, 0x7b,
	0x81, 0x47, 0xa3, 0xff, 0x21, 0x7f, 0x25, 0x3b, 0x58, 0x44, 0xee, 0x97, 0xfd, 0xf8, 0x37, 0x00,
	0x00, 0xff, 0xff, 0x2f, 0xb7, 0xdc, 0x78, 0xc5, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// LaguSionServiceClient is the client API for LaguSionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LaguSionServiceClient interface {
	ListSongs(ctx context.Context, in *ListSongRequest, opts ...grpc.CallOption) (*ListSongResponse, error)
}

type laguSionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLaguSionServiceClient(cc grpc.ClientConnInterface) LaguSionServiceClient {
	return &laguSionServiceClient{cc}
}

func (c *laguSionServiceClient) ListSongs(ctx context.Context, in *ListSongRequest, opts ...grpc.CallOption) (*ListSongResponse, error) {
	out := new(ListSongResponse)
	err := c.cc.Invoke(ctx, "/lagusion.LaguSionService/ListSongs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LaguSionServiceServer is the server API for LaguSionService service.
type LaguSionServiceServer interface {
	ListSongs(context.Context, *ListSongRequest) (*ListSongResponse, error)
}

// UnimplementedLaguSionServiceServer can be embedded to have forward compatible implementations.
type UnimplementedLaguSionServiceServer struct {
}

func (*UnimplementedLaguSionServiceServer) ListSongs(ctx context.Context, req *ListSongRequest) (*ListSongResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSongs not implemented")
}

func RegisterLaguSionServiceServer(s *grpc.Server, srv LaguSionServiceServer) {
	s.RegisterService(&_LaguSionService_serviceDesc, srv)
}

func _LaguSionService_ListSongs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSongRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LaguSionServiceServer).ListSongs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lagusion.LaguSionService/ListSongs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LaguSionServiceServer).ListSongs(ctx, req.(*ListSongRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _LaguSionService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "lagusion.LaguSionService",
	HandlerType: (*LaguSionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListSongs",
			Handler:    _LaguSionService_ListSongs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lagu_sion.proto",
}
