// Code generated by protoc-gen-go. DO NOT EDIT.
// source: lagu_sion.proto

package lagusion

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SongBook int32

const (
	SongBook_ALL                     SongBook = 0
	SongBook_LAGU_SION               SongBook = 1
	SongBook_LAGU_SION_EDISI_LENGKAP SongBook = 2
)

var SongBook_name = map[int32]string{
	0: "ALL",
	1: "LAGU_SION",
	2: "LAGU_SION_EDISI_LENGKAP",
}

var SongBook_value = map[string]int32{
	"ALL":                     0,
	"LAGU_SION":               1,
	"LAGU_SION_EDISI_LENGKAP": 2,
}

func (x SongBook) String() string {
	return proto.EnumName(SongBook_name, int32(x))
}

func (SongBook) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4ac555336d8700ef, []int{0}
}

type Verse struct {
	Contents             []string `protobuf:"bytes,1,rep,name=contents,proto3" json:"contents,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Verse) Reset()         { *m = Verse{} }
func (m *Verse) String() string { return proto.CompactTextString(m) }
func (*Verse) ProtoMessage()    {}
func (*Verse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ac555336d8700ef, []int{0}
}

func (m *Verse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Verse.Unmarshal(m, b)
}
func (m *Verse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Verse.Marshal(b, m, deterministic)
}
func (m *Verse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Verse.Merge(m, src)
}
func (m *Verse) XXX_Size() int {
	return xxx_messageInfo_Verse.Size(m)
}
func (m *Verse) XXX_DiscardUnknown() {
	xxx_messageInfo_Verse.DiscardUnknown(m)
}

var xxx_messageInfo_Verse proto.InternalMessageInfo

func (m *Verse) GetContents() []string {
	if m != nil {
		return m.Contents
	}
	return nil
}

type Song struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Number               int32    `protobuf:"varint,2,opt,name=number,proto3" json:"number,omitempty"`
	Title                string   `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Verses               []*Verse `protobuf:"bytes,4,rep,name=verses,proto3" json:"verses,omitempty"`
	Reff                 *Verse   `protobuf:"bytes,5,opt,name=reff,proto3" json:"reff,omitempty"`
	SongBook             SongBook `protobuf:"varint,6,opt,name=song_book,json=songBook,proto3,enum=lagusion.SongBook" json:"song_book,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Song) Reset()         { *m = Song{} }
func (m *Song) String() string { return proto.CompactTextString(m) }
func (*Song) ProtoMessage()    {}
func (*Song) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ac555336d8700ef, []int{1}
}

func (m *Song) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Song.Unmarshal(m, b)
}
func (m *Song) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Song.Marshal(b, m, deterministic)
}
func (m *Song) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Song.Merge(m, src)
}
func (m *Song) XXX_Size() int {
	return xxx_messageInfo_Song.Size(m)
}
func (m *Song) XXX_DiscardUnknown() {
	xxx_messageInfo_Song.DiscardUnknown(m)
}

var xxx_messageInfo_Song proto.InternalMessageInfo

func (m *Song) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Song) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *Song) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Song) GetVerses() []*Verse {
	if m != nil {
		return m.Verses
	}
	return nil
}

func (m *Song) GetReff() *Verse {
	if m != nil {
		return m.Reff
	}
	return nil
}

func (m *Song) GetSongBook() SongBook {
	if m != nil {
		return m.SongBook
	}
	return SongBook_ALL
}

type ListSongsRequest struct {
	SongBook             SongBook `protobuf:"varint,1,opt,name=song_book,json=songBook,proto3,enum=lagusion.SongBook" json:"song_book,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListSongsRequest) Reset()         { *m = ListSongsRequest{} }
func (m *ListSongsRequest) String() string { return proto.CompactTextString(m) }
func (*ListSongsRequest) ProtoMessage()    {}
func (*ListSongsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ac555336d8700ef, []int{2}
}

func (m *ListSongsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListSongsRequest.Unmarshal(m, b)
}
func (m *ListSongsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListSongsRequest.Marshal(b, m, deterministic)
}
func (m *ListSongsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListSongsRequest.Merge(m, src)
}
func (m *ListSongsRequest) XXX_Size() int {
	return xxx_messageInfo_ListSongsRequest.Size(m)
}
func (m *ListSongsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListSongsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListSongsRequest proto.InternalMessageInfo

func (m *ListSongsRequest) GetSongBook() SongBook {
	if m != nil {
		return m.SongBook
	}
	return SongBook_ALL
}

type ListSongResponse struct {
	Songs                *Song    `protobuf:"bytes,1,opt,name=songs,proto3" json:"songs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListSongResponse) Reset()         { *m = ListSongResponse{} }
func (m *ListSongResponse) String() string { return proto.CompactTextString(m) }
func (*ListSongResponse) ProtoMessage()    {}
func (*ListSongResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ac555336d8700ef, []int{3}
}

func (m *ListSongResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListSongResponse.Unmarshal(m, b)
}
func (m *ListSongResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListSongResponse.Marshal(b, m, deterministic)
}
func (m *ListSongResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListSongResponse.Merge(m, src)
}
func (m *ListSongResponse) XXX_Size() int {
	return xxx_messageInfo_ListSongResponse.Size(m)
}
func (m *ListSongResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListSongResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListSongResponse proto.InternalMessageInfo

func (m *ListSongResponse) GetSongs() *Song {
	if m != nil {
		return m.Songs
	}
	return nil
}

func init() {
	proto.RegisterEnum("lagusion.SongBook", SongBook_name, SongBook_value)
	proto.RegisterType((*Verse)(nil), "lagusion.Verse")
	proto.RegisterType((*Song)(nil), "lagusion.Song")
	proto.RegisterType((*ListSongsRequest)(nil), "lagusion.ListSongsRequest")
	proto.RegisterType((*ListSongResponse)(nil), "lagusion.ListSongResponse")
}

func init() { proto.RegisterFile("lagu_sion.proto", fileDescriptor_4ac555336d8700ef) }

var fileDescriptor_4ac555336d8700ef = []byte{
	// 389 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0x51, 0x6b, 0x9c, 0x40,
	0x14, 0x85, 0x33, 0xeb, 0x6a, 0xf5, 0xa6, 0xd9, 0x95, 0x4b, 0x49, 0xc5, 0xbc, 0x88, 0x29, 0x54,
	0xfa, 0xe0, 0x82, 0x7d, 0xe9, 0x5b, 0xb1, 0x8d, 0x84, 0xa5, 0x92, 0x96, 0x91, 0xf6, 0x55, 0x62,
	0x32, 0x2b, 0x12, 0x33, 0xb3, 0x75, 0xc6, 0x40, 0xff, 0x4c, 0xff, 0x4c, 0xff, 0x58, 0x19, 0x5d,
	0x77, 0x49, 0x09, 0x25, 0x6f, 0x9e, 0x39, 0x87, 0xef, 0x1e, 0xef, 0x85, 0x65, 0x7b, 0x5d, 0xf7,
	0xa5, 0x6c, 0x04, 0x8f, 0xb7, 0x9d, 0x50, 0x02, 0x6d, 0xfd, 0xa0, 0xb5, 0x7f, 0x56, 0x0b, 0x51,
	0xb7, 0x6c, 0x35, 0xbc, 0x57, 0xfd, 0x66, 0xc5, 0xee, 0xb7, 0xea, 0xd7, 0x18, 0x0b, 0xcf, 0xc1,
	0xfc, 0xc1, 0x3a, 0xc9, 0xd0, 0x07, 0xfb, 0x46, 0x70, 0xc5, 0xb8, 0x92, 0x1e, 0x09, 0x8c, 0xc8,
	0xa1, 0x7b, 0x1d, 0xfe, 0x21, 0x30, 0x2f, 0x04, 0xaf, 0x71, 0x01, 0xb3, 0xe6, 0xd6, 0x23, 0x01,
	0x89, 0x4e, 0xe8, 0xac, 0xb9, 0xc5, 0x53, 0xb0, 0x78, 0x7f, 0x5f, 0xb1, 0xce, 0x9b, 0x05, 0x24,
	0x32, 0xe9, 0x4e, 0xe1, 0x2b, 0x30, 0x55, 0xa3, 0x5a, 0xe6, 0x19, 0x01, 0x89, 0x1c, 0x3a, 0x0a,
	0x7c, 0x0b, 0xd6, 0x83, 0x9e, 0x25, 0xbd, 0x79, 0x60, 0x44, 0xc7, 0xc9, 0x32, 0x9e, 0x3a, 0xc6,
	0x43, 0x07, 0xba, 0xb3, 0xf1, 0x1c, 0xe6, 0x1d, 0xdb, 0x6c, 0x3c, 0x33, 0x20, 0x4f, 0xc5, 0x06,
	0x13, 0x57, 0xe0, 0x48, 0xc1, 0xeb, 0xb2, 0x12, 0xe2, 0xce, 0xb3, 0x02, 0x12, 0x2d, 0x12, 0x3c,
	0x24, 0x75, 0xdd, 0x4f, 0x42, 0xdc, 0x51, 0x5b, 0xee, 0xbe, 0xc2, 0xcf, 0xe0, 0xe6, 0x8d, 0x54,
	0xda, 0x91, 0x94, 0xfd, 0xec, 0x99, 0x54, 0x8f, 0x21, 0xe4, 0x19, 0x90, 0x0f, 0x07, 0x08, 0x65,
	0x72, 0x2b, 0xb8, 0x64, 0xf8, 0x06, 0x4c, 0xed, 0xcb, 0x01, 0x70, 0x9c, 0x2c, 0x1e, 0x03, 0xe8,
	0x68, 0xbe, 0xfb, 0x08, 0xf6, 0xc4, 0xc3, 0x17, 0x60, 0xa4, 0x79, 0xee, 0x1e, 0xe1, 0x09, 0x38,
	0x79, 0x7a, 0xf9, 0xbd, 0x2c, 0xd6, 0x5f, 0xaf, 0x5c, 0x82, 0x67, 0xf0, 0x7a, 0x2f, 0xcb, 0xec,
	0x62, 0x5d, 0xac, 0xcb, 0x3c, 0xbb, 0xba, 0xfc, 0x92, 0x7e, 0x73, 0x67, 0xc9, 0x6f, 0x02, 0xcb,
	0xfc, 0xba, 0xee, 0x8b, 0x46, 0xf0, 0x82, 0x75, 0x0f, 0xcd, 0x0d, 0xc3, 0x0b, 0x78, 0xa9, 0xeb,
	0xa4, 0x6d, 0x3b, 0xfc, 0x16, 0x9e, 0xc6, 0xe3, 0xb1, 0xe3, 0xe9, 0xd8, 0x71, 0xa6, 0x8f, 0xed,
	0xfb, 0x87, 0x4e, 0xff, 0xd6, 0x0f, 0x8f, 0x30, 0x03, 0x67, 0xbf, 0x19, 0x7c, 0x22, 0x3a, 0xad,
	0xeb, 0xff, 0x98, 0xca, 0x1a, 0x86, 0xbe, 0xff, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x00, 0x60, 0x64,
	0x79, 0x8c, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// LaguSionServiceClient is the client API for LaguSionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LaguSionServiceClient interface {
	ListAllSongs(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ListSongResponse, error)
	ListSongs(ctx context.Context, in *ListSongsRequest, opts ...grpc.CallOption) (*ListSongResponse, error)
}

type laguSionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLaguSionServiceClient(cc grpc.ClientConnInterface) LaguSionServiceClient {
	return &laguSionServiceClient{cc}
}

func (c *laguSionServiceClient) ListAllSongs(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ListSongResponse, error) {
	out := new(ListSongResponse)
	err := c.cc.Invoke(ctx, "/lagusion.LaguSionService/ListAllSongs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *laguSionServiceClient) ListSongs(ctx context.Context, in *ListSongsRequest, opts ...grpc.CallOption) (*ListSongResponse, error) {
	out := new(ListSongResponse)
	err := c.cc.Invoke(ctx, "/lagusion.LaguSionService/ListSongs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LaguSionServiceServer is the server API for LaguSionService service.
type LaguSionServiceServer interface {
	ListAllSongs(context.Context, *empty.Empty) (*ListSongResponse, error)
	ListSongs(context.Context, *ListSongsRequest) (*ListSongResponse, error)
}

// UnimplementedLaguSionServiceServer can be embedded to have forward compatible implementations.
type UnimplementedLaguSionServiceServer struct {
}

func (*UnimplementedLaguSionServiceServer) ListAllSongs(ctx context.Context, req *empty.Empty) (*ListSongResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAllSongs not implemented")
}
func (*UnimplementedLaguSionServiceServer) ListSongs(ctx context.Context, req *ListSongsRequest) (*ListSongResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSongs not implemented")
}

func RegisterLaguSionServiceServer(s *grpc.Server, srv LaguSionServiceServer) {
	s.RegisterService(&_LaguSionService_serviceDesc, srv)
}

func _LaguSionService_ListAllSongs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LaguSionServiceServer).ListAllSongs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lagusion.LaguSionService/ListAllSongs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LaguSionServiceServer).ListAllSongs(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _LaguSionService_ListSongs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSongsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LaguSionServiceServer).ListSongs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lagusion.LaguSionService/ListSongs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LaguSionServiceServer).ListSongs(ctx, req.(*ListSongsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _LaguSionService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "lagusion.LaguSionService",
	HandlerType: (*LaguSionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListAllSongs",
			Handler:    _LaguSionService_ListAllSongs_Handler,
		},
		{
			MethodName: "ListSongs",
			Handler:    _LaguSionService_ListSongs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lagu_sion.proto",
}
